name: ArcadiaCore
main: net.arcadia.arcadiacore.ArcadiaCore
version: 1.0.0
api-version: '1.21'
author: Kuvvii
description: Master plugin for ArcadiaMC

softdepend:
  - Vault
  - VaultUnlocked
  - Essentials

commands:

  deposit:
    description: Deposit gold into your account.
    usage: "/deposit <amount> <currency>"

  wallet:
    description: View your currency balances.
    usage: "/wallet"

  arc:
    description: Main Arcadia command.
    usage: "/arc help"
    aliases: [arcadia]

  arcad:
    description: Arcadia admin command.
    usage: "/arcad <subcommand>"
    permission: arcadia.admin

  emote:
    description: Arcadia emotes.
    usage: "/emote <kiss|mog|smack> [player]"

  ademote:
    description: Admin emotes.
    usage: "/ademote <shinderu|poof|smite|supermog> [player]"

  modcall:
    description: Request staff assistance.
    usage: "/modcall"

  priest:
    description: Priest commands.
    usage: "/priest marry <player1> <player2>"
    permission: arcadia.priest

  neco:
    description: National economics.
    usage: "/neco <subcommand>"
    permission: arcadia.neco

  eco:
    description: Global economics commands.
    usage: "/eco <currencylist|exchange>"
    permission: arcadia.eco

  adeco:
    description: Admin economics commands.
    usage: "/adeco <subcommand>"
    permission: arcadia.adeco

  tadmin:
    description: Towny religion admin commands.
    usage: "/tadmin <subcommand>"
    permission: arcadia.tadmin

  shika:
    description: Deer.
    usage: "/shika"

  sail:
    description: Boost your boat with Sail.
    usage: "/sail"
